### ISSUE TITLE
Problem when I reload my Skript

### ISSUE THREAD

**Issue by plambert684** [Sitrica/ServerInstances#9]
Hello, When skript load my skript with this code, I have an error : 
```
command /testserver:
     trigger:
           create a new bungeecord server named "UHC" from template "lobby"
```

```
[17:51:06] [Server thread/INFO]: [Skript] Loading variables...[m
[17:51:06] [Server thread/INFO]: [Skript] Loaded 0 variables in 0.0 seconds[m
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:51:06] [Server thread/ERROR]: #!#! Could not load server.sk
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:51:06] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:51:06] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:51:06] [Server thread/ERROR]: #!#! Here is full list of them:
[17:51:06] [Server thread/ERROR]: #!#! Skungee v1.0.6b skript-db v1.3.9 
[17:51:06] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:51:06] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:51:06] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:51:06] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:51:06] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:51:06] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Stack trace:
[17:51:06] [Server thread/ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: me.limeglass.skungee.spigot.elements.effects.EffBungeeShutdownServer
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[17:51:06] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82)
[17:51:06] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1259)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[17:51:06] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[17:51:06] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: Missing closing bracket ']' [pattern: (stop|shutdown) bungee[[ ]cord] server[s] %strings% [(and|with) [serverinstances] saving %-boolean%]
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.nextBracket(SkriptParser.java:1102)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:76)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[17:51:06] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[17:51:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[17:51:06] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82)
[17:51:06] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1259)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017)
[17:51:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[17:51:06] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Version Information:
[17:51:06] [Server thread/ERROR]: #!#!   Skript: 2.6.4 (latest)
[17:51:06] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:51:06] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[17:51:06] [Server thread/ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[17:51:06] [Server thread/ERROR]: #!#!   Minecraft: 1.19.4
[17:51:06] [Server thread/ERROR]: #!#!   Java: 17.0.6 (OpenJDK 64-Bit Server VM 17.0.6+10-Ubuntu-0ubuntu122.04)
[17:51:06] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.102-1-pve
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Current node: create a new bungeecord server named "UHC" from template "lobby" (server.sk, line 3)
[17:51:06] [Server thread/ERROR]: #!#! Current item: null
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Thread: Server thread
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! Language: english
[17:51:06] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/ERROR]: #!#! End of Error.
[17:51:06] [Server thread/ERROR]: #!#! 
[17:51:06] [Server thread/INFO]: [Skript] All scripts loaded without errors.[m
[17:51:06] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 0 triggers and 0 commands in 0.07 seconds[m
[17:51:06] [Server thread/INFO]: [Skript] Finished loading.[m
```

Skript Version : 2.6.4
Skungee Version : 1.0.6b
ServerInstances : 1.0.4
Java Version : 17
Spigot version : 1.19.4
Bungeecord version : lasted

**Comment by TheLimeGlass** [comment]
Use skungee 2.0.0

**Comment by plambert684** [comment]
Thanks for your reply ! 
Ok, I will go to use Skungee 2.0.0 and ServerInstance 2.0.1.
What Java and Spigot Version and is required ?

**Comment by plambert684** [comment]
and Skript Version ?

**Comment by TheLimeGlass** [comment]
Doesn't matter, supports Java 8 to 17 and Skript 2.7.0-beta2
